name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Install dependencies
        run: |
          uv pip install --upgrade pip
          uv pip install -r requirements.txt

      - name: Run tests and measure coverage
        run: |
          make coverage

      - name: Upload coverage to SonarQube
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          organization: 'Asankhey'
          projectKey: 'python-project-50'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Lint code
        run: make lint
