name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install uv
        run: curl -Ls https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: uv pip install --editable .[dev]

      - name: Lint
        run: make lint

      - name: Run tests
        run: make test
