name: Python CI

on:
  push:
    branches: [main]

jobs:
  python-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install uv
        run: curl -Ls https://astral.sh/uv/install.sh | sh

      - name: Set up virtual environment
        run: uv venv

      - name: Install dependencies
        run: uv pip install --editable .[dev]

      - name: Run linter
        run: make lint

      - name: Run tests
        run: make test

